(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(ansi-color-names-vector ["black" "light gray" "dark gray" "light slate gray"])
 '(async-bytecomp-package-mode t)
 '(custom-safe-themes
   '("6a24250040a9777e8d2e1c2310c6e26cfa12fb11d1ecc8a8de5b9705ff0227b8" "b486c4c5f8597e0b8401bc960cc878151a335d20e052ba3c9da27f12881877a2" "39dd7106e6387e0c45dfce8ed44351078f6acd29a345d8b22e7b8e54ac25bac4" "e26e879d250140e0d4c4d5ab457c32bcb29742599bd28c1ce31301344c6f2a11" "cc0dbb53a10215b696d391a90de635ba1699072745bf653b53774706999208e3" default))
 '(erc-hide-list '("JOIN" "PART" "QUIT"))
 '(erc-nick "yyyyy")
 '(inhibit-startup-screen t)
 '(initial-buffer-choice t)
 '(message-kill-buffer-on-exit t)
 '(nrepl-message-colors
   '("#032f62" "#6a737d" "#d73a49" "#6a737d" "#005cc5" "#6f42c1" "#d73a49" "#6a737d"))
 '(org-modules
   '(org-bbdb org-bibtex org-docview org-info org-irc org-man org-toc org-velocity))
 '(org-support-shift-select t)
 '(org-velocity-always-use-bucket t)
 '(org-velocity-bucket "/var/shortcuts/notes/notes.org.gpg")
 '(package-archives
   '(("gnu" . "http://elpa.gnu.org/packages/")
     ("melpa" . "http://melpa.org/packages/")
     ("org" . "http://orgmode.org/elpa/")))
 '(package-selected-packages
   '(color-theme-modern late-night late-night-theme zone-nyan yasnippet which-key wgrep vagrant-tramp vagrant use-package toml-mode systemd switch-window sr-speedbar spaceline salt-mode rg restclient-helm rebox2 rainbow-delimiters racer pyenv-mode purple-haze-theme org-plus-contrib org-bullets org-beautify-theme nyan-mode nix-mode nginx-mode mustache-mode mustache multiple-cursors monokai-alt-theme markdown-mode magit less-css-mode ledger-mode keychain-environment jq-mode jinja2-mode intero info+ helm-unicode helm-pass helm-mu helm-ls-git helm-bibtex hasky-stack god-mode go-errcheck go-eldoc github-modern-theme fold-this flycheck-yamllint flycheck-rust flycheck-ledger exotica-theme exec-path-from-shell epresent elm-mode eink-theme dockerfile-mode diminish company-terraform company-quickhelp company-go company-bibtex company-ansible company-anaconda cargo basic-theme auctex-latexmk ansible-doc ansible ace-jump-mode 0blayout))
 '(scroll-bar-mode nil)
 '(speedbar-show-unknown-files t)
 '(speedbar-use-images nil)
 '(speedbar-verbosity-level 0)
 '(sr-speedbar-auto-refresh nil)
 '(sublimity-mode t t))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(agda2-highlight-coinductive-constructor-face ((t (:foreground "hot pink"))))
 '(agda2-highlight-datatype-face ((t (:foreground "cyan"))))
 '(agda2-highlight-error-face ((t (:foreground "firebrick1" :underline nil))))
 '(agda2-highlight-field-face ((t (:foreground "hot pink"))))
 '(agda2-highlight-function-face ((t (:foreground "cyan"))))
 '(agda2-highlight-inductive-constructor-face ((t (:foreground "hot pink"))))
 '(agda2-highlight-keyword-face ((t (:foreground "medium orchid"))))
 '(agda2-highlight-module-face ((t (:foreground "cyan"))))
 '(agda2-highlight-number-face ((t (:foreground "lawn green"))))
 '(agda2-highlight-postulate-face ((t (:foreground "cyan"))))
 '(agda2-highlight-primitive-face ((t (:foreground "medium spring green"))))
 '(agda2-highlight-primitive-type-face ((t (:foreground "medium spring green"))))
 '(agda2-highlight-record-face ((t (:foreground "cyan"))))
 '(agda2-highlight-string-face ((t (:foreground "light coral"))))
 '(company-scrollbar-bg ((t (:background "gray18" :underline nil :weight normal))))
 '(company-scrollbar-fg ((t (:background "slate blue" :underline nil :weight normal))))
 '(company-tooltip ((t (:background "gray18" :foreground "light gray" :underline nil :weight normal))))
 '(company-tooltip-annotation ((t (:foreground "light slate blue" :underline nil :weight normal))))
 '(company-tooltip-common ((t (:foreground "medium slate blue" :underline nil :weight normal))))
 '(company-tooltip-selection ((t (:background "black" :foreground "violet red" :underline nil :weight normal))))
 '(font-latex-italic-face ((t (:inherit italic :foreground "powder blue"))))
 '(font-latex-math-face ((t (:foreground "light sky blue"))))
 '(font-latex-sectioning-5-face ((t (:foreground "orchid"))))
 '(font-latex-slide-title-face ((t (:inherit font-lock-type-face :weight bold :height 1.2))))
 '(font-latex-string-face ((t (:foreground "deep pink"))))
 '(font-latex-verbatim-face ((t (:inherit fixed-pitch :foreground "hot pink"))))
 '(helm-M-x-key ((t (:foreground "orchid" :underline nil :weight normal))))
 '(helm-buffer-archive ((t (:foreground "white" :underline nil :weight normal))))
 '(helm-buffer-directory ((t (:background "gray18" :foreground "gray" :underline nil :weight normal))))
 '(helm-buffer-file ((t (:foreground "white" :underline nil :weight normal))))
 '(helm-buffer-not-saved ((t (:foreground "gainsboro" :underline nil :weight normal))))
 '(helm-buffer-process ((t (:foreground "gainsboro" :underline nil :weight normal))))
 '(helm-buffer-saved-out ((t (:background "black" :foreground "light gray" :underline nil :weight normal))))
 '(helm-candidate-number ((t (:foreground "dark gray" :underline nil :weight normal))))
 '(helm-ff-directory ((t (:background "black" :foreground "dark gray" :underline nil :weight normal))))
 '(helm-ff-dotted-directory ((t (:background "black" :foreground "dim gray" :underline nil :weight normal))))
 '(helm-ff-dotted-symlink-directory ((t (:background "black" :foreground "dark gray" :underline nil :weight normal))))
 '(helm-ff-executable ((t (:foreground "white smoke" :underline nil :weight normal))))
 '(helm-ff-file ((t (:foreground "white" :underline nil :weight normal))))
 '(helm-ff-invalid-symlink ((t (:background "gainsboro" :foreground "black" :underline nil :weight normal))))
 '(helm-ff-prefix ((t (:background "gainsboro" :foreground "black" :underline nil :weight normal))))
 '(helm-ff-symlink ((t (:foreground "gainsboro" :underline nil :weight normal))))
 '(helm-header ((t (:inherit header-line :background "black" :foreground "white smoke"))))
 '(helm-header-line-left-margin ((t (:foreground "white smoke" :underline nil :weight normal))))
 '(helm-history-remote ((t (:foreground "gainsboro" :underline nil :weight normal))))
 '(helm-match ((t (:foreground "white" :underline nil :weight normal))))
 '(helm-match-item ((t (:background "black" :foreground "white" :underline nil :weight normal))))
 '(helm-prefarg ((t (:foreground "gainsboro"))))
 '(helm-selection ((t (:background "dim gray" :underline nil :weight normal))))
 '(helm-separator ((t (:foreground "gray" :underline nil :weight normal))))
 '(helm-source-header ((t (:foreground "gainsboro" :height 1.3))))
 '(helm-visible-mark ((t (:foreground "white"))))
 '(magit-section-heading ((t (:foreground "white smoke" :weight bold))))
 '(speedbar-button-face ((t (:foreground "dark gray" :underline nil :weight normal))))
 '(speedbar-directory-face ((t (:foreground "gray" :underline nil :weight normal))))
 '(speedbar-file-face ((t (:foreground "gainsboro" :underline nil :weight normal))))
 '(speedbar-highlight-face ((t (:background "black" :foreground "white smoke" :underline nil :weight normal))))
 '(speedbar-selected-face ((t (:background "white smoke" :foreground "black" :underline nil :weight normal))))
 '(speedbar-tag-face ((t (:foreground "gray" :underline nil :weight normal)))))
